### ISSUE TITLE
Tapping on document details preview shows another file

### ISSUE THREAD

**Issue by seth100** [ligi/PassAndroid#217] opened 2018-10-01 10:45 UTC
Hi,

when tapping on a document (pdf or image) it should show it in a bigger view so that I can also zoom on it.
The issue is that in my case, when I tap one file, it shows another file the other view, not the current right one.
I have discovered it shows the previously opened one.
To summarize it:

1. Open document A from list view;
2. When in preview, click on it;
3. It should show a detailed view of the same file, not of another one.

Thanks for your work, I hope you can fix it soon!
Regards

**Comment by ligi** [comment] 2018-10-01 11:03
Thanks for the report! Unfortunately I am unable to reproduce the problem - hence I will not be able to fix it. If you have any hints on how to reproduce the problem - please let me know.

**Comment by simontb** [comment] 2018-10-05 18:44
Just noticed this issue today as well. When clicking on a barcode, the barcode of the next pass is shown in fullscreen mode. This might also be related to #218.

Do not have this on my local version with 9d2300bd0a818db0e5b30d25646713c8f9e5f97b being the latest commit, so assume the bug was introduced later.

**Comment by simontb** [comment] 2018-10-05 19:14
Weirdly I don't have this issue when running the current master from Android Studio.

**Comment by simontb** [comment] 2018-10-13 06:16
@ligi could you rebuild the app an upload a signed apk here, that I can install as an update? If this solves the issue, it could be rolled out.

**Comment by DinStamou** [comment] 2018-11-08 21:40
I have the same issue, you need to have multiple passes in the app the same time, and always if you click to the last bar-code it shows the previous one.

**Comment by fungs** [comment] 2018-11-26 04:43
Same issue here! Preview shows previously openend qr code.

**Comment by MichaWen** [comment] 2018-12-11 07:01
same issue here. If you have exact one pass in a category and double-tap the qr code, the correct code is displayed. With two or more passes it shows the qr code from the previous pass. My workaround is moving passes to or from the archive and hold only the actual needed pass in the other category.

**Comment by irgendwr** [comment] 2019-03-10 15:35
This bug was introduced by my pull request #212 (due to fragments in ViewPager preloading and overwriting currentPass), sorry about that.

This will be fixed with pull request #221

**Closed** 2019-03-10 16:58 UTC

**Comment by hooger** [comment] 2019-04-13 09:25
Until the PR goes online a possible workaround: tap edit and close on the ticket. This (to my experience) tricks the app to treat current ticket as the last one and opens it in big. Hope it helps!

**Comment by simontb** [comment] 2019-05-18 03:26
@ligi could you update the app in Play Store, so the bugfix goes live? If not done yet also on the other stores.
