### ISSUE TITLE
Dialog disappearance may reduce user experience

### ISSUE THREAD

**Issue by Chou95** [ligi/PassAndroid#379] opened 2023-01-28 09:20 UTC
Hi, dear developers!

# General information
my device: android 10

There exist some dialog disappearance after screen rotation. I think that screen rotation shouldn't do damange to the UI state. The re-created UI should be the same as before rotation, Right?

I think it is not hard to save the UI state of these dialogs by saving the return value of dialog.isShowing(). In this way, you can decide whether to re-open these dialogs when the phone rotation and UI recreation occur. This may improve the user experience, do you think so?

# Snapshot details
### before rotation
![NO3-BEFORE](https://user-images.githubusercontent.com/111506060/215258155-9ccf45ef-32e9-45b6-a6c5-006cd491f562.png)

### after rotation 
![NO3-AFTER](https://user-images.githubusercontent.com/111506060/215258161-3506a618-2985-4f45-af08-fa147e12be7b.png)

### before rotation
![NO4-BEFORE](https://user-images.githubusercontent.com/111506060/215258131-830edc95-9af8-4fa7-8892-6c7557027fcb.png)

### after rotation 
![NO4-AFTER](https://user-images.githubusercontent.com/111506060/215258139-891b0fea-766f-476b-b57f-7d3e92464e7e.png)

### before rotation
![NO5-BEFORE](https://user-images.githubusercontent.com/111506060/215258082-ccc848c0-2958-4617-914f-dccee419e7f9.png)
### after rotation 
![NO5-AFTER](https://user-images.githubusercontent.com/111506060/215258087-81dfaeac-dd74-4421-aa2a-c8c5dfa79d90.png)

**Comment by ligi** [comment] 2023-04-10 19:42
Thanks - but duplicate of #127

**Closed by ligi** 2023-04-10 19:42 UTC
Labels: bug
