### ISSUE TITLE
.pkpass file association

### ISSUE THREAD

**Issue by panache67** [ligi/PassAndroid#53] opened 2016-01-26 21:05 UTC
If I try to open a .pkpass attached to an email directly from the Gmail client, I receive a message saying 'You don't have an app that can open this file (.pkpass)...' Would be great if you could register PassAndroid as .pkpass file handler in one of the next versions. Many thanks!

**Comment by ligi** [comment] 2016-03-01 08:30
Just tried it - also with gmail - could not reproduce it - so I have to close this - when you have more details on how to reproduce the problem feel free to reopen

**Closed by ligi** 2016-03-01 08:30 UTC

**Comment by sytolk** [comment] 2016-07-27 13:06
@panache67  what is your Gmail client ? web browser

**Comment by panache67** [comment] 2016-07-27 20:05
@sytolk I am using the Gmail app version 6.6.126913422 on a Nexus 5 with Android 6.0.1 patch level 5 July 2016.

**Comment by ligi** [comment] 2016-07-27 22:34
@panache67 can you install intent-intercept and send me a screenshot of it with the intent thrown with the pkpass file?
