### ISSUE TITLE
pkpass files from Wiener Konzerthaus never open

### ISSUE THREAD

**Issue by eighthave** [ligi/PassAndroid#452] opened 2023-05-06 13:33 UTC
I have successfully used this app for airline tickets.  Now I tried with concert tickets.  The three attached files are from Wiener Konzerthaus, but opening them in PassAndroid just gave me the screen saying "Bitte warten, sollte nicht lange dauern" (please wait, it shouldn't take a long time"., which it was stuck at forever

I'm happy to dig in to debug it if you can give me some guidance.  I've never worked with _pkpass_ files before.

~~(GitHub is currently not letting me upload a screenshot, nor the _pkpass_ files in a ZIP.  I'll try again soon).~~

[Konzerthaus-pkpass-files.zip](https://github.com/ligi/PassAndroid/files/11419008/Konzerthaus-pkpass-files.zip)

**Comment by Tuffiglig** [comment] 2023-05-10 05:07
Same for me with Edinburgh Castle Tickets

**Comment by jtorrex** [comment] 2023-05-10 12:26
I'm experiencing the same trying to import any kind of pkpass files. Before the last release, it was working without any problem.

**Comment by nottheend** [comment] 2023-05-12 11:41
I also experience this with a "Deutschland-ticket" (see also #438).

However, after installing version 3.5.7 as suggested in #434 and importing the ticket on that version, it works.
And also after upgrading afterwards I can still open the already imported ticket

**Comment by eighthave** [comment] 2023-05-18 10:33
I tried again with a new concert ticket, this time on 3.7.1, and got the same result: endless spinner.  I reverted to 3.5.7 and it works!

**Comment by ligi** [comment] 2023-05-18 10:44
Thanks for the feedback - I released a new version 3.7.3 which is rolling out to beta on play and to fdroid - would be great to know if the problem is gone there - thanks!

**Comment by MatthewVernon** [comment] 2023-05-18 10:46
Thanks! I'll give it a go once it reaches f-droid :)

**Comment by MatthewVernon** [comment] 2023-05-20 19:40
@ligi 3.7.3 from f-droid works for me now, thank you!

**Comment by Tuffiglig** [comment] 2023-05-20 23:46
Same for me.
3.7.3 is working again.

**Comment by jtorrex** [comment] 2023-05-21 14:20
Working again! Thanks @ligi!!!

**Comment by ligi** [comment] 2023-05-21 16:39
Great! Thanks for the feedback and sorry for introducing the error.
Closing this issue then.

**Closed by ligi** 2023-05-21 16:39 UTC
